"use strict";

const { API_VERSION } = require("../Constants");

module.exports.API_URL = `/api/v${API_VERSION}`;
module.exports.CDN_URL = "https://cdn.discordapp.com";
module.exports.DISCORD_URL = "https://discord.com";

module.exports.CHANNEL = (channelID) => `/channels/${channelID}`;
module.exports.CHANNEL_BULK_DELETE = (channelID) => `/channels/${channelID}/messages/bulk-delete`;
module.exports.CHANNEL_CALL_RING = (channelID) => `/channels/${channelID}/call/ring`;
module.exports.CHANNEL_CROSSPOST = (channelID, msgID) => `/channels/${channelID}/messages/${msgID}/crosspost`;
module.exports.CHANNEL_FOLLOW = (channelID) => `/channels/${channelID}/followers`;
module.exports.CHANNEL_INVITES = (channelID) => `/channels/${channelID}/invites`;
module.exports.CHANNEL_MESSAGE_REACTION = (channelID, msgID, reaction) => `/channels/${channelID}/messages/${msgID}/reactions/${reaction}`;
module.exports.CHANNEL_MESSAGE_REACTION_USER = (channelID, msgID, reaction, userID) => `/channels/${channelID}/messages/${msgID}/reactions/${reaction}/${userID}`;
module.exports.CHANNEL_MESSAGE_REACTIONS = (channelID, msgID) => `/channels/${channelID}/messages/${msgID}/reactions`;
module.exports.CHANNEL_MESSAGE = (channelID, msgID) => `/channels/${channelID}/messages/${msgID}`;
module.exports.CHANNEL_MESSAGES = (channelID) => `/channels/${channelID}/messages`;
module.exports.CHANNEL_MESSAGES_SEARCH = (channelID) => `/channels/${channelID}/messages/search`;
module.exports.CHANNEL_PERMISSION = (channelID, overID) => `/channels/${channelID}/permissions/${overID}`;
module.exports.CHANNEL_PERMISSIONS = (channelID) => `/channels/${channelID}/permissions`;
module.exports.CHANNEL_PIN = (channelID, msgID) => `/channels/${channelID}/pins/${msgID}`;
module.exports.CHANNEL_PINS = (channelID) => `/channels/${channelID}/pins`;
module.exports.CHANNEL_RECIPIENT = (groupID, userID) => `/channels/${groupID}/recipients/${userID}`;
module.exports.CHANNEL_TYPING = (channelID) => `/channels/${channelID}/typing`;
module.exports.CHANNEL_WEBHOOKS = (channelID) => `/channels/${channelID}/webhooks`;
module.exports.CHANNELS = "/channels";
module.exports.CUSTOM_EMOJI_GUILD = (emojiID) => `/emojis/${emojiID}/guild`;
module.exports.DISCOVERY_CATEGORIES = "/discovery/categories";
module.exports.DISCOVERY_VALIDATION = "/discovery/valid-term";
module.exports.GATEWAY = "/gateway";
module.exports.GATEWAY_BOT = "/gateway/bot";
module.exports.GUILD = (guildID) => `/guilds/${guildID}`;
module.exports.GUILD_AUDIT_LOGS = (guildID) => `/guilds/${guildID}/audit-logs`;
module.exports.GUILD_BAN = (guildID, memberID) => `/guilds/${guildID}/bans/${memberID}`;
module.exports.GUILD_BANS = (guildID) => `/guilds/${guildID}/bans`;
module.exports.GUILD_CHANNELS = (guildID) => `/guilds/${guildID}/channels`;
module.exports.GUILD_DISCOVERY = (guildID) => `/guilds/${guildID}/discovery-metadata`;
module.exports.GUILD_DISCOVERY_CATEGORY = (guildID, categoryID) => `/guilds/${guildID}/discovery-categories/${categoryID}`;
module.exports.GUILD_EMOJI = (guildID, emojiID) => `/guilds/${guildID}/emojis/${emojiID}`;
module.exports.GUILD_EMOJIS = (guildID) => `/guilds/${guildID}/emojis`;
module.exports.GUILD_INTEGRATION = (guildID, integrationID) => `/guilds/${guildID}/integrations/${integrationID}`;
module.exports.GUILD_INTEGRATION_SYNC = (guildID, integrationID) => `/guilds/${guildID}/integrations/${integrationID}/sync`;
module.exports.GUILD_INTEGRATIONS = (guildID) => `/guilds/${guildID}/integrations`;
module.exports.GUILD_INVITES = (guildID) => `/guilds/${guildID}/invites`;
module.exports.GUILD_VANITY_URL = (guildID) => `/guilds/${guildID}/vanity-url`;
module.exports.GUILD_MEMBER = (guildID, memberID) => `/guilds/${guildID}/members/${memberID}`;
module.exports.GUILD_MEMBER_NICK = (guildID, memberID) => `/guilds/${guildID}/members/${memberID}/nick`;
module.exports.GUILD_MEMBER_ROLE = (guildID, memberID, roleID) => `/guilds/${guildID}/members/${memberID}/roles/${roleID}`;
module.exports.GUILD_MEMBERS = (guildID) => `/guilds/${guildID}/members`;
module.exports.GUILD_MEMBERS_SEARCH = (guildID) => `/guilds/${guildID}/members/search`;
module.exports.GUILD_MESSAGES_SEARCH = (guildID) => `/guilds/${guildID}/messages/search`;
module.exports.GUILD_PREVIEW = (guildID) => `/guilds/${guildID}/preview`;
module.exports.GUILD_PRUNE = (guildID) => `/guilds/${guildID}/prune`;
module.exports.GUILD_ROLE = (guildID, roleID) => `/guilds/${guildID}/roles/${roleID}`;
module.exports.GUILD_ROLES = (guildID) => `/guilds/${guildID}/roles`;
module.exports.GUILD_TEMPLATE = (code) => `/guilds/templates/${code}`;
module.exports.GUILD_TEMPLATES = (guildID) => `/guilds/${guildID}/templates`;
module.exports.GUILD_TEMPLATE_GUILD = (guildID, code) => `/guilds/${guildID}/templates/${code}`;
module.exports.GUILD_VOICE_REGIONS = (guildID) => `/guilds/${guildID}/regions`;
module.exports.GUILD_WEBHOOKS = (guildID) => `/guilds/${guildID}/webhooks`;
module.exports.GUILD_WELCOME_SCREEN = (guildID) => `/guilds/${guildID}/welcome-screen`;
module.exports.GUILD_WIDGET = (guildID) => `/guilds/${guildID}/widget.json`;
module.exports.GUILD_WIDGET_SETTINGS = (guildID) => `/guilds/${guildID}/widget`;
module.exports.GUILD_VOICE_STATE = (guildID, user) => `/guilds/${guildID}/voice-states/${user}`;
module.exports.GUILDS = "/guilds";
module.exports.INVITE = (inviteID) => `/invites/${inviteID}`;
module.exports.OAUTH2_APPLICATION = (applicationID) => `/oauth2/applications/${applicationID}`;
module.exports.USER = (userID) => `/users/${userID}`;
module.exports.USER_BILLING = (userID) => `/users/${userID}/billing`;
module.exports.USER_BILLING_PAYMENTS = (userID) => `/users/${userID}/billing/payments`;
module.exports.USER_BILLING_PREMIUM_SUBSCRIPTION = (userID) => `/users/${userID}/billing/premium-subscription`;
module.exports.USER_CHANNELS = (userID) => `/users/${userID}/channels`;
module.exports.USER_CONNECTIONS = (userID) => `/users/${userID}/connections`;
module.exports.USER_CONNECTION_PLATFORM = (userID, platform, ID) => `/users/${userID}/connections/${platform}/${ID}`;
module.exports.USER_GUILD = (userID, guildID) => `/users/${userID}/guilds/${guildID}`;
module.exports.USER_GUILDS = (userID) => `/users/${userID}/guilds`;
module.exports.USER_MFA_CODES = (userID) => `/users/${userID}/mfa/codes`;
module.exports.USER_MFA_TOTP_DISABLE = (userID) => `/users/${userID}/mfa/totp/disable`;
module.exports.USER_MFA_TOTP_ENABLE = (userID) => `/users/${userID}/mfa/totp/enable`;
module.exports.USER_NOTE = (userID, targetID) => `/users/${userID}/note/${targetID}`;
module.exports.USER_PROFILE = (userID) => `/users/${userID}/profile`;
module.exports.USER_RELATIONSHIP = (userID, relID) => `/users/${userID}/relationships/${relID}`;
module.exports.USER_SETTINGS = (userID) => `/users/${userID}/settings`;
module.exports.USERS = "/users";
module.exports.VOICE_REGIONS = "/voice/regions";
module.exports.WEBHOOK = (hookID) => `/webhooks/${hookID}`;
module.exports.WEBHOOK_MESSAGE = (hookID, token, msgID) => `/webhooks/${hookID}/${token}/messages/${msgID}`;
module.exports.WEBHOOK_SLACK = (hookID) => `/webhooks/${hookID}/slack`;
module.exports.WEBHOOK_TOKEN = (hookID, token) => `/webhooks/${hookID}/${token}`;
module.exports.WEBHOOK_TOKEN_SLACK = (hookID, token) => `/webhooks/${hookID}/${token}/slack`;

// CDN Endpoints
module.exports.ACHIEVEMENT_ICON = (applicationID, achievementID, icon) => `/app-assets/${applicationID}/achievements/${achievementID}/icons/${icon}`;
module.exports.APPLICATION_ASSET = (applicationID, asset) => `/app-assets/${applicationID}/${asset}`;
module.exports.APPLICATION_ICON = (applicationID, icon) => `/app-icons/${applicationID}/${icon}`;
module.exports.CHANNEL_ICON = (channelID, channelIcon) => `/channel-icons/${channelID}/${channelIcon}`;
module.exports.CUSTOM_EMOJI = (emojiID) => `/emojis/${emojiID}`;
module.exports.DEFAULT_USER_AVATAR = (userDiscriminator) => `/embed/avatars/${userDiscriminator}`;
module.exports.GUILD_BANNER = (guildID, guildBanner) => `/banners/${guildID}/${guildBanner}`;
module.exports.GUILD_DISCOVERY_SPLASH = (guildID, guildDiscoverySplash) => `/discovery-splashes/${guildID}/${guildDiscoverySplash}`;
module.exports.GUILD_ICON = (guildID, guildIcon) => `/icons/${guildID}/${guildIcon}`;
module.exports.GUILD_SPLASH = (guildID, guildSplash) => `/splashes/${guildID}/${guildSplash}`;
module.exports.TEAM_ICON = (teamID, teamIcon) => `/team-icons/${teamID}/${teamIcon}`;
module.exports.USER_AVATAR = (userID, userAvatar) => `/avatars/${userID}/${userAvatar}`;

// Client Endpoints
module.exports.MESSAGE_LINK = (guildID, channelID, messageID) => `/channels/${guildID}/${channelID}/${messageID}`;